name: CI/CD Pipeline 🚀 (Test & Deploy)

# Controls when the workflow should run
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets necessary permissions for deployment
permissions:
  contents: write 
  pages: write    
  id-token: write 

# A sequence of jobs
jobs:
  # 1. Test Job: Installs dependencies and runs all tests
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test -- --ci --watchAll=false

  # 2. Deploy Job: Only runs if the 'test' job succeeds
  deploy:
    name: Deploy to GitHub Pages
    needs: test 
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install

      - name: Run gh-pages Deployment Script (Authenticated)
        run: |
          # 1. Set Git user details for the deploy commit created by gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 2. Construct the authenticated repository URL using the GITHUB_TOKEN
          REPO_URL="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          
          # 3. Run the deploy script, passing the authenticated URL via the --repo flag
          npm run deploy -- -r $REPO_URL
          
      - name: Deployment Finished (for logging and URL output)
        id: deployment
        run: echo "Deployment to gh-pages completed."
